### ISSUE TITLE
Resque worker auto stop on production????

### ISSUE THREAD

**Issue by weilluo** [nevans/resque-pool#147]
My resque-pool.yml

```yaml
high: 1
medium: 1
low: 1

production:
  low: 2
  medium: 3
  high: 4

staging:
  low: 1
  medium: 2
  high: 3
```

Start job command `bundle exec resque-pool --daemon --config config/resque_pool.yml`,  I didn't know why all of the workers stopped automatically.

And this are some error messages:

```
/home/ubuntu/.rvm/gems/ruby-2.1.4/gems/resque-pool-0.6.0/lib/resque/pool.rb:389:in `fork': Cannot allocate memory - fork(2) (Errno::ENOMEM)
from /home/ubuntu/.rvm/gems/ruby-2.1.4/gems/resque-pool-0.6.0/lib/resque/pool.rb:389:in `spawn_worker!'
from /home/ubuntu/.rvm/gems/ruby-2.1.4/gems/resque-pool-0.6.0/lib/resque/pool.rb:367:in `block in spawn_missing_workers_for'
from /home/ubuntu/.rvm/gems/ruby-2.1.4/gems/resque-pool-0.6.0/lib/resque/pool.rb:366:in `times'
from /home/ubuntu/.rvm/gems/ruby-2.1.4/gems/resque-pool-0.6.0/lib/resque/pool.rb:366:in `spawn_missing_workers_for'
from /home/ubuntu/.rvm/gems/ruby-2.1.4/gems/resque-pool-0.6.0/lib/resque/pool.rb:352:in `block in maintain_worker_count'
```
