### ISSUE TITLE
Workers counter increases after restarting

### ISSUE THREAD

**Issue by gorkunov** [nevans/resque-pool#97]
I configured pool with 7 workers:

```yaml
---
stats: 1
comments: 2
apns: 2
candidate_posts: 1
'reprocess_comments,user_ban': 1
```

and my resque.rake looks like:

```ruby
require 'resque/tasks'
task 'resque:setup' => :environment do
  Resque.before_fork = Proc.new { ActiveRecord::Base.establish_connection }
end

task "resque:pool:setup" do
  ActiveRecord::Base.connection.disconnect!
  Resque::Pool.after_prefork do
    ActiveRecord::Base.establish_connection
    Resque.redis.client.reconnect
  end
end
```

Running resque-pool as:
```
resque: INTERVAL=0.5 TERM_CHILD=1 RESQUE_TERM_TIMEOUT=10 bundle exec resque-pool
```

After several heroku deploys I see (resque web server):
1 of 26 Workers Working
Also sometimes I handled stale workers after restarting.
